### DISCUSSION TITLE
Implement a basic CI/CD

### DISCUSSION THREAD

**Discussion by DaniAsh551** [DeckCheatz/wemod-launcher#45] [Ideas]
I was thinking, we may benefit from some form of CI/CD to do basic sanity checks (like linting) while submitting any given commit.
This can be a start and we can see how we can improve from there.

A basic debian/archlinux runner with python should be fine.

Later, we can add conditions for doing more extensive checks than simple linting. Maybe even move to some form of version system if that would help??

What do you think @marvin1099 @JohnHamwi ?

**Comment by DaniAsh551** [comment]
to add to the previous message, we could also adopt a sane branching strategy once we get the CI/CD functional, where the main branch will always be stable. Development will happen on other branches.

**Reply by marvin1099** [reply]
I thought about a dev branch to, that one would be simple, i would say we do that one.
Next a CI/CD system for that we would probably need something like a GitHub action,  
that can check, something like the syntax.
I think that would be nice but i have no idea on how these work,  
if you or @JohnHamwi have some idea on how to do it, than it sound good by me.

**Reply by DaniAsh551** [reply]
Dont worry about it, I can make a good enough CI/CD.

I mentioned this to you because you are the only developer who is active on this.

So, I'll write some actions/tasks and enable them and let you know

**Reply by marvin1099** [reply]
by the way can you tell me what this branch was for [feat/deref](https://github.com/DaniAsh551/wemod-launcher/tree/feat/deref),  
I don't think its relevant anymore so i like to remove it, but i don't want to delete anything important. 
Also i have created a "dev" branch, so now I push to that fist and merge after I'm sure it works.

**Reply by marvin1099** [reply]
> Dont worry about it, I can make a good enough CI/CD.
> 
> I mentioned this to you because you are the only developer who is active on this.
> 
> So, I'll write some actions/tasks and enable them and let you know

Sounds great.

**Reply by DaniAsh551** [reply]
I would say, at this point, anything other than the main branch is not really needed.

Deref was to test the functionality to dereference all the symlinks in the prefix (this prevented WeMod from working on anything except GE7-35 in the past). But its been merged into main since then

**Comment by DaniAsh551** [comment]
Instead of a single dev branch where development will happen, we can also follow feature branching if youd prefer that, but a Dev branch should work just fine for us

Once the CI matures, we can even implement auto PR/merge to main too if the checks pass

**Reply by marvin1099** [reply]
> Instead of a single dev branch where development will happen, we can also follow feature branching if youd prefer that, but a Dev branch should work just fine for us
> 
> Once the CI matures, we can even implement auto PR/merge to main too if the checks pass

Sounds good as well.

**Comment by marvin1099** [comment]
so since you don't have lots of time i checked some stuff and i saw the Pyre workflow, that might work.
That would be a basic CI system, but it also seems that  Type Annotations will need to be added in this case,
but that is simple enough to figure out for me.
I also added some code that will merge from dev.
Tell me what you have thought of 

That file will be in the workflows folder later
```
name: Pyre

on:
  workflow_dispatch:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
    contents: read

jobs:
  pyre:
    permissions:
      actions: read
      contents: read
      security-events: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Run Pyre
        uses: facebook/pyre-action@60697a7858f7cc8470d8cc494a3cf2ad6b06560d
        with:
          # To customize these inputs:
          # See https://github.com/facebook/pyre-action#inputs
          repo-directory: './'
          requirements-path: 'requirements.txt'

      - name: Auto-merge to main on successful checks
        if: github.ref == 'refs/heads/dev' && success()
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout main
          git merge dev
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
